# Configuration for TTRPG PDF Content Extraction
# This file defines settings for the enhanced PDF analyzer

# Output Configuration
output:
  directory: "./extracted_content"
  format: "json"  # json, csv, or both
  compress: false  # Whether to compress output files
  
# Cache Configuration  
cache:
  directory: "./extraction_cache"
  ttl_days: 30  # Cache time-to-live in days
  max_size_gb: 10  # Maximum cache size in GB
  
# Processing Configuration
processing:
  use_multiprocessing: true
  max_workers: null  # null = use all CPU cores
  batch_size: 10  # PDFs to process before checkpoint
  retry_failed: true
  max_retries: 3
  timeout_per_pdf: 600  # seconds
  
# OCR Configuration
ocr:
  enabled: true
  dpi: 150  # Image resolution for OCR
  max_pages: 50  # Maximum pages to OCR per PDF
  timeout_per_page: 300  # seconds
  language: "eng"  # Tesseract language code
  optimize_for: "speed"  # speed or accuracy
  
# Text Extraction Configuration
extraction:
  min_text_length: 100  # Minimum characters for successful extraction
  sample_size: 10000  # Characters to sample for genre classification
  page_limit: 500  # Maximum pages to process per PDF
  
# Genre Classification Configuration
genre_classification:
  confidence_threshold: 0.5
  use_filename: true
  use_content: true
  fallback_genre: "GENERIC"
  
# Content Pattern Matching
patterns:
  races:
    enabled: true
    min_confidence: 0.3
    max_per_page: 10
  classes:
    enabled: true
    min_confidence: 0.3
    max_per_page: 10
  npcs:
    enabled: true
    min_confidence: 0.3
    max_per_page: 20
  equipment:
    enabled: true
    min_confidence: 0.3
    max_per_page: 30
    
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "pdf_extraction.log"
  max_size_mb: 100
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Progress Tracking
progress:
  show_eta: true
  update_interval: 1  # seconds
  save_checkpoints: true
  checkpoint_interval: 5  # PDFs between checkpoints
  
# Quality Control
quality:
  validate_output: true
  min_extraction_rate: 0.1  # Minimum content extraction rate
  generate_reports: true
  report_format: "detailed"  # summary or detailed
  
# Resource Limits
resources:
  max_memory_gb: 8
  max_file_size_mb: 500
  temp_directory: "/tmp/pdf_extraction"
  clean_temp_on_exit: true
  
# API Integration (for future MCP server)
api:
  enabled: false
  endpoint: "http://localhost:8000/api/extraction"
  auth_token: ""
  batch_upload: true
  
# Notification Settings
notifications:
  enabled: false
  email:
    smtp_server: ""
    smtp_port: 587
    from_address: ""
    to_addresses: []
    on_completion: true
    on_error: true
  webhook:
    url: ""
    on_completion: true
    on_error: true