[package]
name = "ttrpg-assistant"
version = "1.0.0"
description = "TTRPG Assistant Desktop Application"
authors = ["TTRPG Assistant Team"]
license = "MIT"
repository = "https://github.com/Raudbjorn/MDMAI"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.1", features = [] }

[dependencies]
tauri = { version = "2.1", features = ["tray-icon", "image-png", "image-ico"] }
tauri-plugin-clipboard-manager = "2.1"
tauri-plugin-dialog = "2.1"
tauri-plugin-fs = "2.1"
tauri-plugin-http = "2.1"
tauri-plugin-notification = "2.1"
tauri-plugin-process = "2.1"
tauri-plugin-shell = "2.1"
tauri-plugin-updater = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
sysinfo = "0.30"
chrono = { version = "0.4", features = ["serde"] }
# Data Management Dependencies
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid", "json"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
argon2 = "0.5"
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
zstd = "0.13"
tar = "0.4"
walkdir = "2.0"
blake3 = "1.0"
futures = "0.3"
tokio-stream = "0.1"
bytes = "1.5"
thiserror = "1.0"
tempfile = "3.8"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "ttrpg-assistant"
path = "src/main.rs"
